name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.4
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ github.TOKEN }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive .
      - name: Run terraform init
        run: terraform init
      - name: Run terraform validate
        run: terraform validate
      # Print TFLint version
      - name: Run tflint checks
        run: |
          tflint --version
          # Install plugins
          tflint --init
          # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
          tflint -f compact --recursive
  security-check:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@v2
    # Tfsec - Security scanner for your Terraform code
    - name: Run Tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
