name: Build/Test

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # v1
        with:
          terraform_version: 1.6.4
      - uses: terraform-linters/setup-tflint@444635365d380c7363d1eaee4267317c2445717d # v2
        name: Setup TFLint
        with:
          github_token: ${{ github.TOKEN }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive .
      - name: Run terraform init
        run: terraform init
      - name: Run terraform validate
        run: terraform validate
      # Print TFLint version
      - name: Run tflint checks
        run: |
          tflint --version
          # Install plugins
          tflint --init
          # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
          tflint -f compact --recursive
  security-check:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    # Tfsec - Security scanner for your Terraform code
    - name: Run Tfsec
      uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
