name: Build/Test

on:
  workflow_call:

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.6.4
      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
        name: Setup TFLint
        with:
          github_token: ${{ github.TOKEN }}
      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive .
      - name: Run terraform init
        run: terraform init
      - name: Run terraform validate
        run: terraform validate
      # Print TFLint version
      - name: Run tflint checks
        run: |
          tflint --version
          # Install plugins
          tflint --init
          # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
          tflint -f compact --recursive
  Test:
    name: Run terraform tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.11.2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@1c7c9a30d7d233e26e7a4fc1505cc44bbd937229
        with:
          provider: lxd
      - name: Run Main Module Tests
        run: |
          terraform init && terraform test
      - name: Run Subcluster Module Tests
        working-directory: ./modules/subcluster
        run: |
          terraform init && terraform test
  security-check:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
    # Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    # Tfsec - Security scanner for your Terraform code
    - name: Run Tfsec
      uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
